version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=slavik
      - POSTGRES_PASSWORD=mipassword
      - POSTGRES_DB=framing
    ports:
      - "5433:5432"  # Asegura que el puerto expuesto es accesible
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
